### PR TITLE
1deg_jra55do_iaf: update OM3 executable to latest version

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
Changes needed to use latest OM3 executable.

Contributes to https://github.com/COSIMA/access-om3/issues/118

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
Unfortunately this currently does not run. It crashes with the following error:

```
 *** WAVEWATCH III ERROR IN W3IOGR :
     UNEXPECTED SOURCE TERM IDENTIFIER 3
          IN mod_def.ww3 FILE : Ice sink term (Wang and Shen) 
    EXPECTED FROM switch FILE : ------------------------------
     MOD DEF FILE WAS GENERATED WITH A DIFFERENT            
     WW3 VERSION OR USING A DIFFERENT SWITCH FILE.          
     MAKE SURE WW3_GRID IS COMPILED WITH SAME SWITCH        
     AS WW3_SHEL OR WW3_MULTI, RUN WW3_GRID AGAIN           
     AND THEN TRY AGAIN THE PROGRAM YOU JUST USED.          
```

@ezhilsabareesh8 Do you know how to fix this?

**Comment by dougiesquire** [comment]
Yeah, I think this configuration is currently broken for the current switches - see https://github.com/COSIMA/MOM6-CICE6-WW3/pull/17

**Comment by micaeljtoliveira** [comment]
Thanks. Shall we then simply merge this as is, without testing? Or leave it open or now?

**Comment by ezhilsabareesh8** [comment]
Hi @micaeljtoliveira , the executables needs to be updated in the bin directory to match the `mod_def` files. The following executable of the [ww3_execs_to_bin](https://github.com/COSIMA/access-om3/tree/ww3_execs_to_bin) branch needs to be added to the bin directory.

**Comment by micaeljtoliveira** [comment]
@ezhilsabareesh8 I'm using spack to build and install the executables, not the `build.sh` script. With Spack all gets properly installed:

```bash
$ ls /g/data/ik11/spack/0.21.2/opt/linux-rocky8-cascadelake/intel-2021.10.0/access-om3-main-6pue372/bin/
access-om3-CICE6-WW3  access-om3-MOM6-CICE6  access-om3-MOM6-CICE6-WW3  ww3_grid  ww3_ounf  ww3_ounp  ww3_outf  ww3_strt
```

**Comment by ezhilsabareesh8** [comment]
@micaeljtoliveira This branch [1deg_jra55do_iaf_iss118](https://github.com/COSIMA/MOM6-CICE6-WW3/tree/1deg_jra55do_iaf_iss118) is compatible with the [WW3_switches](https://github.com/COSIMA/access-om3/commits/2ea2920de5437a461eaa4bbfae378927adc44e00) access-om3 build, the changes are not pushed to `access-om3` main branch since we are in the process of finalising switches for wave attenuation and dissipation model

**Comment by micaeljtoliveira** [comment]
Ah, okay. Then I think it's best to leave this open until you're done with updating the switches.

**Comment by ezhilsabareesh8** [comment]
I have created a [pull request](https://github.com/COSIMA/access-om3/pull/131) in `access-om3`, I think we can merge these changes to `access-om3` main since current `IC3` switch works reasonably well and we can modify the switches later if needed.

**Comment by micaeljtoliveira** [comment]
@ezhilsabareesh8 I've now tried to run this branch with the OM3 version that includes the changes from https://github.com/COSIMA/access-om3/pull/131, but I still get the same error.

As we have also updated the WW3 version in OM3, don't we need to regenerate the `mod_def` files?

**Comment by ezhilsabareesh8** [comment]
> As we have also updated the WW3 version in OM3, don't we need to regenerate the `mod_def` files?

Hi @micaeljtoliveira, yes `mod_def` files need to be generated with the new executables, I did that and copied it to `ik11` inputs directory. It should work now.

**Comment by micaeljtoliveira** [comment]
@ezhilsabareesh8 Thanks! Seems to work correctly now.

**Comment by ezhilsabareesh8** [comment]
However, I found something weird from the `wav.log`, the input file `ww3_shel.nml` is completely ignored and no input field is being passed or output is requested. 

```

  Input fields :
 --------------------------------------------------
       ice param. 1   ---/NO
       ice param. 2   ---/NO
       ice param. 3   ---/NO
       ice param. 4   ---/NO
       ice param. 5   ---/NO
       mud density    ---/NO
       mud thkness    ---/NO
       mud viscos.    ---/NO
       water levels   ---/NO
       currents       ---/NO
       winds          ---/NO
       ice fields     ---/NO
       momentum       ---/NO
       air density    ---/NO
       mean param.    ---/NO
       1D spectra     ---/NO
       2D spectra     ---/NO

            Fields   : no fields defined
```

**Comment by micaeljtoliveira** [comment]
@ezhilsabareesh8 I suggest we merge this nevertheless, and fix any remaining issue in a different PR.

**Comment by ezhilsabareesh8** [comment]
> @ezhilsabareesh8 I suggest we merge this nevertheless, and fix any remaining issue in a different PR.

Sounds good to me, I am looking into this issues, will open a separate PR

**Comment by ezhilsabareesh8** [comment]
This PR can be closed, I opened a separate issue [#143](https://github.com/COSIMA/access-om3/issues/143) to address the changes with updated WW3 component.

**Review by ezhilsabareesh8 — APPROVED** [review]
Looks good to me. The updated OM3 executable is working and the compatible `mod_def.ww3` and `restart.ww3` are added in `ik11/inputs/` directory.

**Pull request merged**
