### PR TITLE
Merge changes from MOM6-CICE6

### PR DESCRIPTION
**Pull request by anton-seaice**

### CODE REVIEW

**Comment by anton-seaice** [comment]
I believe this is correct, but we need to merge #23 first to confirm.

**Review by ezhilsabareesh8 — CHANGES_REQUESTED** [review]
I think `fsd` related parameters are required in MOM6-CICE6-WW3 configurations, for example, `tr_fsd` shouldn't be removed from `ice_in` unless it is `true` by default.

**Comment by anton-seaice** [comment]
Oops. Thanks. Ill fix tomorrow.

I can't see any other mistakes - all the fsd history parameters are unchanged ?

**Comment by ezhilsabareesh8** [comment]
> all the fsd history parameters are unchanged ?

The following history parameters are unchanged however `restart_fsd = .false.` is ommited not sure what it actually does

```
&icefields_fsd_nml
    f_fsdrad       = 'md' 
```

**Comment by anton-seaice** [comment]
Ok thanks - yes we need that too to get it to read fsd from the cice restart file!

 https://cice-consortium-cice.readthedocs.io/en/main/user_guide/ug_case_settings.html#tracer-nml

**Review by ezhilsabareesh8 — COMMENTED** [review]
Is it is ok to use the same initial conditions for both the RYF and IAF configurations?, It's the same in MOM6-CICE6 configs as well. 

`ice_ic = "./input/iced.1900-01-01-10800.nc"`

**Comment by anton-seaice** [comment]
Yeah I think that is fine. Its not perfect. But the ice will be kinda of close, and the ice will stabilise much quicker than the ocean will. So it seems ok from that perspective.

**Review by ezhilsabareesh8 — APPROVED** [review]
Looks good to me

**Comment by anton-seaice** [comment]
Ah. This doesn't run anymore:

```
 (abort_ice)ABORTED: 
 (abort_ice) called from ice_restart.F90
 (abort_ice) line number          744
 (abort_ice) error = 
 (ice_pio_check)NetCDF: Variable not found, (read_restart_field) ERROR: missing 
 varid fsd001
```

Because our ic file doesnt include fsd

We must have missed this in the RYF config too.

(Not sure how to make the best fsd initial conditions, or whether to fix this some other way!)

**Comment by ezhilsabareesh8** [comment]
> (Not sure how to make the best fsd initial conditions, or whether to fix this some other way!)

Maybe we can set the `ice_ic` to default for now?, I think `fsd` initial conditions cannot be generated from CICE5?

> We must have missed this in the RYF config too.

Yes, `restart_fsd` is set to false in RYF.

**Comment by anton-seaice** [comment]
I think setting ice_ic to default would be troublesome, it gives a very unrealistic ice area. We could leave `restart_fsd` as false and create a new issue to resolve it.

**Comment by anton-seaice** [comment]
Ah. It looks like `restart_fsd=.false.` was correct. If the runtime is continue, this gets turned on in the driver, otherwise it initialises internally:

https://github.com/CICE-Consortium/CICE/blob/0af031d785d3bc622cd19af48a2e9465b5abe9a0/cicecore/drivers/nuopc/cmeps/CICE_InitMod.F90#L373

**Comment by anton-seaice** [comment]
If `runtype=initial` (and `restart_fsd=.false.`) then it will initialise fsd using the `init_fsd` call 

If `runtype=continue` or `restart_fsd=.true.` in `ice_in`, then it will try to read fsd from the restart/ic file

**Comment by anton-seaice** [comment]
This works and generates output and history files for each component. Doesn't restart due to still pointing to a binary before https://github.com/COSIMA/access-om3/pull/160 was included

**Pull request merged**
