### PR TITLE
Use ACCESS-OM2 grid, topography and initial conditions

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
This PR moves the gmom_jra_wd configuration to ACCESS-OM2 1 deg grid, topography, and initial conditions. The changes to the forcing, ice and ocean are the same as cosima/mom6-cice6#6.

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
This is currently not working as we need to update the grid maps to/from ww3.

@dougiesquire How did you handle this for the ocean and ice?

**Comment by dougiesquire** [comment]
I simply removed them, as they should get computed on-the-fly if they aren't provided as inputs. It's only a temporary solution really; in the long run we'll want to generate and provide these

**Comment by micaeljtoliveira** [comment]
Thanks, I'll try that. 

What about the WW3 mesh? Shall we leave it unchanged for now, as there's no equivalent mesh in OM2? @aekiss Any thoughts on that?

**Comment by dougiesquire** [comment]
@ezhilsabareesh8 is now able to generate a `mod_def.ww3` file for the 1deg tripolar grid. With that, he's able to use the same mesh I generated for the [1deg MOM6-CICE6 configuration](https://github.com/COSIMA/MOM6-CICE6/tree/1deg_jra55do_ryf) (`/g/data/ik11/inputs/access-om3/0.x.0/1deg/access-om2-1deg-ESMFmesh.nc`).

So yes, I'd suggest leaving as is for this PR, and @ezhilsabareesh8 can update soon.

**Comment by micaeljtoliveira** [comment]
This now runs for one month without any issue.

**Comment by dougiesquire** [comment]
I think `generate_mesh.py` should be removed from this. We don't want multiple versions that could get out of sync. It probably should be moved into it's own repo

**Comment by micaeljtoliveira** [comment]
Good point. I now removed the script.

**Review by dougiesquire — APPROVED** [review]

**Pull request merged**
