### PR TITLE
Use symlink with correct name for WW3 mod_def input

### PR DESCRIPTION
**Pull request by dougiesquire**
See https://github.com/COSIMA/MOM6-CICE6-WW3/issues/2 for context/justification. This shouldn't be merged until https://github.com/payu-org/payu/pull/368 is released.

Closes https://github.com/COSIMA/MOM6-CICE6-WW3/issues/2

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
Ups. I tried fixed your branch while you were opening the new PR, without realizing you deleted and recreated the branch. I'll fix it!

**Comment by dougiesquire** [comment]
Sorry - I wasn't very clear

**Comment by micaeljtoliveira** [comment]
Actually, I think my changes are the correct ones, as they point to the latest sets of inputs. I do need to create the symlink though.

**Comment by micaeljtoliveira** [comment]
Done.

@dougiesquire To be clear, I've created a symlink to` /g/data/ik11/inputs/access-om3/0.x.0/cime/wav/ww3/ww3a.mod_def.ww3.wwver7.14.230705b`, which is actually the latest version of the mod_def input, named `mod_def.ww3`. The PR changes the configuration to use this symlink.

**Comment by aekiss** [comment]
LGTM - is this ready to merge?

**Comment by dougiesquire** [comment]
> LGTM - is this ready to merge?

The [required changes](https://github.com/payu-org/payu/pull/368) in Payu still haven't been released so I think we need to hold off.

**Comment by micaeljtoliveira** [comment]
The required Payu changes have finally been released, so I think we can merge.

**Review by micaeljtoliveira — APPROVED** [review]

**Pull request merged**
